// ORIGINAL: java/DomUtil.java

// Copyright (c) 2020 Markus Mobius
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package domutil

// allowedAttributes is list of all safe HTML attributes.
// Taken from the Chromium source code in:
//   third_party/blink/renderer/core/html/html_attribute_names.json5
// and manually filtered to exclude event handlers.
// Last updated on June 12, 2020.
var allowedAttributes = map[string]struct{}{
	"abbr":                     {},
	"accept-charset":           {},
	"accept":                   {},
	"accesskey":                {},
	"action":                   {},
	"align":                    {},
	"alink":                    {},
	"allow":                    {},
	"allowfullscreen":          {},
	"allowpaymentrequest":      {},
	"alt":                      {},
	"archive":                  {},
	"as":                       {},
	"async":                    {},
	"autocapitalize":           {},
	"autocomplete":             {},
	"autocorrect":              {},
	"autofocus":                {},
	"autoplay":                 {},
	"autopictureinpicture":     {},
	"axis":                     {},
	"background":               {},
	"behavior":                 {},
	"bgcolor":                  {},
	"border":                   {},
	"bordercolor":              {},
	"capture":                  {},
	"cellpadding":              {},
	"cellspacing":              {},
	"char":                     {},
	"challenge":                {},
	"charoff":                  {},
	"charset":                  {},
	"checked":                  {},
	"cite":                     {},
	"class":                    {},
	"classid":                  {},
	"clear":                    {},
	"code":                     {},
	"codebase":                 {},
	"codetype":                 {},
	"color":                    {},
	"cols":                     {},
	"colspan":                  {},
	"compact":                  {},
	"content":                  {},
	"contenteditable":          {},
	"controls":                 {},
	"controlslist":             {},
	"conversiondestination":    {},
	"coords":                   {},
	"crossorigin":              {},
	"csp":                      {},
	"data":                     {},
	"datetime":                 {},
	"declare":                  {},
	"decoding":                 {},
	"default":                  {},
	"defer":                    {},
	"dir":                      {},
	"direction":                {},
	"dirname":                  {},
	"disabled":                 {},
	"disablepictureinpicture":  {},
	"disableremoteplayback":    {},
	"disallowdocumentaccess":   {},
	"download":                 {},
	"draggable":                {},
	"elementtiming":            {},
	"enctype":                  {},
	"end":                      {},
	"enterkeyhint":             {},
	"event":                    {},
	"exportparts":              {},
	"face":                     {},
	"for":                      {},
	"form":                     {},
	"formaction":               {},
	"formenctype":              {},
	"formmethod":               {},
	"formnovalidate":           {},
	"formtarget":               {},
	"frame":                    {},
	"frameborder":              {},
	"headers":                  {},
	"height":                   {},
	"hidden":                   {},
	"high":                     {},
	"href":                     {},
	"hreflang":                 {},
	"hreftranslate":            {},
	"hspace":                   {},
	"http-equiv":               {},
	"id":                       {},
	"imagesizes":               {},
	"imagesrcset":              {},
	"importance":               {},
	"impressiondata":           {},
	"impressionexpiry":         {},
	"incremental":              {},
	"inert":                    {},
	"inputmode":                {},
	"integrity":                {},
	"is":                       {},
	"ismap":                    {},
	"keytype":                  {},
	"kind":                     {},
	"invisible":                {},
	"label":                    {},
	"lang":                     {},
	"language":                 {},
	"latencyhint":              {},
	"leftmargin":               {},
	"link":                     {},
	"list":                     {},
	"loading":                  {},
	"longdesc":                 {},
	"loop":                     {},
	"low":                      {},
	"lowsrc":                   {},
	"manifest":                 {},
	"marginheight":             {},
	"marginwidth":              {},
	"max":                      {},
	"maxlength":                {},
	"mayscript":                {},
	"media":                    {},
	"method":                   {},
	"min":                      {},
	"minlength":                {},
	"multiple":                 {},
	"muted":                    {},
	"name":                     {},
	"nohref":                   {},
	"nomodule":                 {},
	"nonce":                    {},
	"noresize":                 {},
	"noshade":                  {},
	"novalidate":               {},
	"nowrap":                   {},
	"object":                   {},
	"open":                     {},
	"optimum":                  {},
	"part":                     {},
	"pattern":                  {},
	"placeholder":              {},
	"playsinline":              {},
	"ping":                     {},
	"policy":                   {},
	"poster":                   {},
	"preload":                  {},
	"pseudo":                   {},
	"readonly":                 {},
	"referrerpolicy":           {},
	"rel":                      {},
	"reportingorigin":          {},
	"required":                 {},
	"resources":                {},
	"rev":                      {},
	"reversed":                 {},
	"role":                     {},
	"rows":                     {},
	"rowspan":                  {},
	"rules":                    {},
	"sandbox":                  {},
	"scheme":                   {},
	"scope":                    {},
	"scrollamount":             {},
	"scrolldelay":              {},
	"scrolling":                {},
	"select":                   {},
	"selected":                 {},
	"shadowroot":               {},
	"shadowrootdelegatesfocus": {},
	"shape":                    {},
	"size":                     {},
	"sizes":                    {},
	"slot":                     {},
	"span":                     {},
	"spellcheck":               {},
	"src":                      {},
	"srcset":                   {},
	"srcdoc":                   {},
	"srclang":                  {},
	"standby":                  {},
	"start":                    {},
	"step":                     {},
	"style":                    {},
	"summary":                  {},
	"tabindex":                 {},
	"target":                   {},
	"text":                     {},
	"title":                    {},
	"topmargin":                {},
	"translate":                {},
	"truespeed":                {},
	"trusttoken":               {},
	"type":                     {},
	"usemap":                   {},
	"valign":                   {},
	"value":                    {},
	"valuetype":                {},
	"version":                  {},
	"vlink":                    {},
	"vspace":                   {},
	"virtualkeyboardpolicy":    {},
	"webkitdirectory":          {},
	"width":                    {},
	"wrap":                     {},
}
