// Code generated by re2c 3.1, DO NOT EDIT.
package re2go

// Original pattern: (?i)(next|weiter|continue|>([^\|]|$)|»([^\|]|$))
func IsNextPaginationLink(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	// Variable for capturing parentheses (twice the number of groups).
	var YYMAXNMATCH int = 1

	yypmatch := make([]int, YYMAXNMATCH*2)
	var yynmatch int
	_ = yynmatch

	// Autogenerated tag variables used by the lexer to track tag values.
	var yyt1 int
	_ = yyt1

	for {
		{
			var yych byte
			yyaccept := 0
			yych = input[cursor]
			switch yych {
			case '>':
				yyt1 = cursor
				goto yy3
			case 'C':
				fallthrough
			case 'c':
				yyt1 = cursor
				goto yy5
			case 'N':
				fallthrough
			case 'n':
				yyt1 = cursor
				goto yy6
			case 'W':
				fallthrough
			case 'w':
				yyt1 = cursor
				goto yy7
			case 0xC2:
				yyt1 = cursor
				goto yy8
			default:
				if limit <= cursor {
					goto yy30
				}
				goto yy1
			}
		yy1:
			cursor++
		yy2:
			{
				continue
			}
		yy3:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0x00:
				fallthrough
			case 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, '\t', '\n', '\v', '\f', '\r', 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, ' ', '!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{':
				fallthrough
			case '}', '~', 0x7F:
				if limit <= cursor {
					goto yy4
				}
				goto yy9
			case 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF:
				goto yy10
			case 0xE0:
				goto yy12
			case 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF:
				goto yy13
			case 0xF0:
				goto yy14
			case 0xF1, 0xF2, 0xF3:
				goto yy15
			case 0xF4:
				goto yy16
			default:
				goto yy4
			}
		yy4:
			yynmatch = 1
			yypmatch[0] = yyt1
			yypmatch[1] = cursor
			{
				// Handle [>»]$
				if yypmatch[1] == limit {
					return true
				} else {
					continue
				}
			}
		yy5:
			yyaccept = 1
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy17
			default:
				goto yy2
			}
		yy6:
			yyaccept = 1
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy18
			default:
				goto yy2
			}
		yy7:
			yyaccept = 1
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy19
			default:
				goto yy2
			}
		yy8:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xBB:
				goto yy3
			default:
				goto yy2
			}
		yy9:
			cursor++
			yynmatch = 1
			yypmatch[0] = yyt1
			yypmatch[1] = cursor
			{
				return true
			}
		yy10:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy9
			default:
				goto yy11
			}
		yy11:
			cursor = marker
			if yyaccept == 0 {
				goto yy4
			} else {
				goto yy2
			}
		yy12:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy10
			default:
				goto yy11
			}
		yy13:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy10
			default:
				goto yy11
			}
		yy14:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy13
			default:
				goto yy11
			}
		yy15:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy13
			default:
				goto yy11
			}
		yy16:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F:
				goto yy13
			default:
				goto yy11
			}
		yy17:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy20
			default:
				goto yy11
			}
		yy18:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'X':
				fallthrough
			case 'x':
				goto yy21
			default:
				goto yy11
			}
		yy19:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy22
			default:
				goto yy11
			}
		yy20:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy23
			default:
				goto yy11
			}
		yy21:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy24
			default:
				goto yy11
			}
		yy22:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy25
			default:
				goto yy11
			}
		yy23:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy26
			default:
				goto yy11
			}
		yy24:
			cursor++
			yynmatch = 1
			yypmatch[0] = yyt1
			yypmatch[1] = cursor
			{
				return true
			}
		yy25:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy27
			default:
				goto yy11
			}
		yy26:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy28
			default:
				goto yy11
			}
		yy27:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy24
			default:
				goto yy11
			}
		yy28:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy29
			default:
				goto yy11
			}
		yy29:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy24
			default:
				goto yy11
			}
		yy30:
			{
				return false
			}
		}

	}
}

// Original pattern: (?i)(prev|early|old|new|<|«)
func IsPrevPaginationLink(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case '<':
				goto yy34
			case 'E':
				fallthrough
			case 'e':
				goto yy35
			case 'N':
				fallthrough
			case 'n':
				goto yy36
			case 'O':
				fallthrough
			case 'o':
				goto yy37
			case 'P':
				fallthrough
			case 'p':
				goto yy38
			case 0xC2:
				goto yy39
			default:
				if limit <= cursor {
					goto yy48
				}
				goto yy32
			}
		yy32:
			cursor++
		yy33:
			{
				continue
			}
		yy34:
			cursor++
			{
				return true
			}
		yy35:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy40
			default:
				goto yy33
			}
		yy36:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy42
			default:
				goto yy33
			}
		yy37:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy43
			default:
				goto yy33
			}
		yy38:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy44
			default:
				goto yy33
			}
		yy39:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xAB:
				goto yy34
			default:
				goto yy33
			}
		yy40:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy45
			default:
				goto yy41
			}
		yy41:
			cursor = marker
			goto yy33
		yy42:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'W':
				fallthrough
			case 'w':
				goto yy34
			default:
				goto yy41
			}
		yy43:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy34
			default:
				goto yy41
			}
		yy44:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy46
			default:
				goto yy41
			}
		yy45:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy47
			default:
				goto yy41
			}
		yy46:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'V':
				fallthrough
			case 'v':
				goto yy34
			default:
				goto yy41
			}
		yy47:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy34
			default:
				goto yy41
			}
		yy48:
			{
				return false
			}
		}

	}
}

// Original pattern: (?i)article|body|content|entry|hentry|main|page|pagination|post|text|blog|story
func IsPositiveToBePagination(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy52
			case 'B':
				fallthrough
			case 'b':
				goto yy53
			case 'C':
				fallthrough
			case 'c':
				goto yy54
			case 'E':
				fallthrough
			case 'e':
				goto yy55
			case 'H':
				fallthrough
			case 'h':
				goto yy56
			case 'M':
				fallthrough
			case 'm':
				goto yy57
			case 'P':
				fallthrough
			case 'p':
				goto yy58
			case 'S':
				fallthrough
			case 's':
				goto yy59
			case 'T':
				fallthrough
			case 't':
				goto yy60
			default:
				if limit <= cursor {
					goto yy92
				}
				goto yy50
			}
		yy50:
			cursor++
		yy51:
			{
				continue
			}
		yy52:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy61
			default:
				goto yy51
			}
		yy53:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy63
			case 'O':
				fallthrough
			case 'o':
				goto yy64
			default:
				goto yy51
			}
		yy54:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy65
			default:
				goto yy51
			}
		yy55:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy66
			default:
				goto yy51
			}
		yy56:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy67
			default:
				goto yy51
			}
		yy57:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy68
			default:
				goto yy51
			}
		yy58:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy69
			case 'O':
				fallthrough
			case 'o':
				goto yy70
			default:
				goto yy51
			}
		yy59:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy71
			default:
				goto yy51
			}
		yy60:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy72
			default:
				goto yy51
			}
		yy61:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy73
			default:
				goto yy62
			}
		yy62:
			cursor = marker
			goto yy51
		yy63:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy74
			default:
				goto yy62
			}
		yy64:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy75
			default:
				goto yy62
			}
		yy65:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy76
			default:
				goto yy62
			}
		yy66:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy77
			default:
				goto yy62
			}
		yy67:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy66
			default:
				goto yy62
			}
		yy68:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy78
			default:
				goto yy62
			}
		yy69:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy79
			default:
				goto yy62
			}
		yy70:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy80
			default:
				goto yy62
			}
		yy71:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy77
			default:
				goto yy62
			}
		yy72:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'X':
				fallthrough
			case 'x':
				goto yy80
			default:
				goto yy62
			}
		yy73:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy81
			default:
				goto yy62
			}
		yy74:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy82
			default:
				goto yy62
			}
		yy75:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy82
			default:
				goto yy62
			}
		yy76:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy83
			default:
				goto yy62
			}
		yy77:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy75
			default:
				goto yy62
			}
		yy78:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy82
			default:
				goto yy62
			}
		yy79:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy82
			case 'I':
				fallthrough
			case 'i':
				goto yy84
			default:
				goto yy62
			}
		yy80:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy82
			default:
				goto yy62
			}
		yy81:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy85
			default:
				goto yy62
			}
		yy82:
			cursor++
			{
				return true
			}
		yy83:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy86
			default:
				goto yy62
			}
		yy84:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy87
			default:
				goto yy62
			}
		yy85:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy88
			default:
				goto yy62
			}
		yy86:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy80
			default:
				goto yy62
			}
		yy87:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy89
			default:
				goto yy62
			}
		yy88:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy82
			default:
				goto yy62
			}
		yy89:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy90
			default:
				goto yy62
			}
		yy90:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy91
			default:
				goto yy62
			}
		yy91:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy78
			default:
				goto yy62
			}
		yy92:
			{
				return false
			}
		}

	}
}

// Original pattern: (?i)combx|comment|com-|contact|foot|footer|footnote|masthead|media|meta|outbrain|promo|related|shoutbox|sidebar|sponsor|shopping|tags|tool|widget
func IsNegativeToBePagination(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yyaccept := 0
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy96
			case 'F':
				fallthrough
			case 'f':
				goto yy97
			case 'M':
				fallthrough
			case 'm':
				goto yy98
			case 'O':
				fallthrough
			case 'o':
				goto yy99
			case 'P':
				fallthrough
			case 'p':
				goto yy100
			case 'R':
				fallthrough
			case 'r':
				goto yy101
			case 'S':
				fallthrough
			case 's':
				goto yy102
			case 'T':
				fallthrough
			case 't':
				goto yy103
			case 'W':
				fallthrough
			case 'w':
				goto yy104
			default:
				if limit <= cursor {
					goto yy170
				}
				goto yy94
			}
		yy94:
			cursor++
		yy95:
			{
				continue
			}
		yy96:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy105
			default:
				goto yy95
			}
		yy97:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy107
			default:
				goto yy95
			}
		yy98:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy108
			case 'E':
				fallthrough
			case 'e':
				goto yy109
			default:
				goto yy95
			}
		yy99:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy110
			default:
				goto yy95
			}
		yy100:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy111
			default:
				goto yy95
			}
		yy101:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy112
			default:
				goto yy95
			}
		yy102:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy113
			case 'I':
				fallthrough
			case 'i':
				goto yy114
			case 'P':
				fallthrough
			case 'p':
				goto yy115
			default:
				goto yy95
			}
		yy103:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy116
			case 'O':
				fallthrough
			case 'o':
				goto yy117
			default:
				goto yy95
			}
		yy104:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy118
			default:
				goto yy95
			}
		yy105:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy119
			case 'N':
				fallthrough
			case 'n':
				goto yy120
			default:
				goto yy106
			}
		yy106:
			cursor = marker
			if yyaccept == 0 {
				goto yy95
			} else {
				goto yy135
			}
		yy107:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy121
			default:
				goto yy106
			}
		yy108:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy122
			default:
				goto yy106
			}
		yy109:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy123
			case 'T':
				fallthrough
			case 't':
				goto yy124
			default:
				goto yy106
			}
		yy110:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy125
			default:
				goto yy106
			}
		yy111:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy126
			default:
				goto yy106
			}
		yy112:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy127
			default:
				goto yy106
			}
		yy113:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy128
			default:
				goto yy106
			}
		yy114:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy129
			default:
				goto yy106
			}
		yy115:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy130
			default:
				goto yy106
			}
		yy116:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy131
			default:
				goto yy106
			}
		yy117:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy132
			default:
				goto yy106
			}
		yy118:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy133
			default:
				goto yy106
			}
		yy119:
			cursor++
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy134
			case 'B':
				fallthrough
			case 'b':
				goto yy136
			case 'M':
				fallthrough
			case 'm':
				goto yy137
			default:
				goto yy106
			}
		yy120:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy138
			default:
				goto yy106
			}
		yy121:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy139
			default:
				goto yy106
			}
		yy122:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy140
			default:
				goto yy106
			}
		yy123:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy124
			default:
				goto yy106
			}
		yy124:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy134
			default:
				goto yy106
			}
		yy125:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy141
			default:
				goto yy106
			}
		yy126:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy142
			default:
				goto yy106
			}
		yy127:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy143
			default:
				goto yy106
			}
		yy128:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy144
			case 'U':
				fallthrough
			case 'u':
				goto yy145
			default:
				goto yy106
			}
		yy129:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy146
			default:
				goto yy106
			}
		yy130:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy147
			default:
				goto yy106
			}
		yy131:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy134
			default:
				goto yy106
			}
		yy132:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy134
			default:
				goto yy106
			}
		yy133:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy148
			default:
				goto yy106
			}
		yy134:
			cursor++
		yy135:
			{
				return true
			}
		yy136:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'X':
				fallthrough
			case 'x':
				goto yy134
			default:
				goto yy106
			}
		yy137:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy149
			default:
				goto yy106
			}
		yy138:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy150
			default:
				goto yy106
			}
		yy139:
			yyaccept = 1
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy151
			case 'N':
				fallthrough
			case 'n':
				goto yy152
			default:
				goto yy135
			}
		yy140:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy153
			default:
				goto yy106
			}
		yy141:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy154
			default:
				goto yy106
			}
		yy142:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy134
			default:
				goto yy106
			}
		yy143:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy155
			default:
				goto yy106
			}
		yy144:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy156
			default:
				goto yy106
			}
		yy145:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy157
			default:
				goto yy106
			}
		yy146:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy158
			default:
				goto yy106
			}
		yy147:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy159
			default:
				goto yy106
			}
		yy148:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy160
			default:
				goto yy106
			}
		yy149:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy160
			default:
				goto yy106
			}
		yy150:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy160
			default:
				goto yy106
			}
		yy151:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy134
			default:
				goto yy106
			}
		yy152:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy161
			default:
				goto yy106
			}
		yy153:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy162
			default:
				goto yy106
			}
		yy154:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy163
			default:
				goto yy106
			}
		yy155:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy164
			default:
				goto yy106
			}
		yy156:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy165
			default:
				goto yy106
			}
		yy157:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy166
			default:
				goto yy106
			}
		yy158:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy151
			default:
				goto yy106
			}
		yy159:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy151
			default:
				goto yy106
			}
		yy160:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy134
			default:
				goto yy106
			}
		yy161:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy167
			default:
				goto yy106
			}
		yy162:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy164
			default:
				goto yy106
			}
		yy163:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy168
			default:
				goto yy106
			}
		yy164:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy134
			default:
				goto yy106
			}
		yy165:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy169
			default:
				goto yy106
			}
		yy166:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy136
			default:
				goto yy106
			}
		yy167:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy134
			default:
				goto yy106
			}
		yy168:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy134
			default:
				goto yy106
			}
		yy169:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy134
			default:
				goto yy106
			}
		yy170:
			{
				return false
			}
		}

	}
}

// Original pattern: (?i)print|archive|comment|discuss|e[\-]?mail|share|reply|all|login|sign|single|as one|article|post|篇
func IsExtraneousToPagination(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy174
			case 'C':
				fallthrough
			case 'c':
				goto yy175
			case 'D':
				fallthrough
			case 'd':
				goto yy176
			case 'E':
				fallthrough
			case 'e':
				goto yy177
			case 'L':
				fallthrough
			case 'l':
				goto yy178
			case 'P':
				fallthrough
			case 'p':
				goto yy179
			case 'R':
				fallthrough
			case 'r':
				goto yy180
			case 'S':
				fallthrough
			case 's':
				goto yy181
			case 0xE7:
				goto yy182
			default:
				if limit <= cursor {
					goto yy223
				}
				goto yy172
			}
		yy172:
			cursor++
		yy173:
			{
				continue
			}
		yy174:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy183
			case 'R':
				fallthrough
			case 'r':
				goto yy185
			case 'S':
				fallthrough
			case 's':
				goto yy186
			default:
				goto yy173
			}
		yy175:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy187
			default:
				goto yy173
			}
		yy176:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy188
			default:
				goto yy173
			}
		yy177:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy189
			case 'M':
				fallthrough
			case 'm':
				goto yy190
			default:
				goto yy173
			}
		yy178:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy191
			default:
				goto yy173
			}
		yy179:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy192
			case 'R':
				fallthrough
			case 'r':
				goto yy193
			default:
				goto yy173
			}
		yy180:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy194
			default:
				goto yy173
			}
		yy181:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy195
			case 'I':
				fallthrough
			case 'i':
				goto yy196
			default:
				goto yy173
			}
		yy182:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0xAF:
				goto yy197
			default:
				goto yy173
			}
		yy183:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy198
			default:
				goto yy184
			}
		yy184:
			cursor = marker
			goto yy173
		yy185:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy199
			case 'T':
				fallthrough
			case 't':
				goto yy200
			default:
				goto yy184
			}
		yy186:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy201
			default:
				goto yy184
			}
		yy187:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy202
			default:
				goto yy184
			}
		yy188:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy203
			default:
				goto yy184
			}
		yy189:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy190
			default:
				goto yy184
			}
		yy190:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy204
			default:
				goto yy184
			}
		yy191:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy205
			default:
				goto yy184
			}
		yy192:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy206
			default:
				goto yy184
			}
		yy193:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy207
			default:
				goto yy184
			}
		yy194:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy208
			default:
				goto yy184
			}
		yy195:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy209
			default:
				goto yy184
			}
		yy196:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy210
			case 'N':
				fallthrough
			case 'n':
				goto yy211
			default:
				goto yy184
			}
		yy197:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x87:
				goto yy198
			default:
				goto yy184
			}
		yy198:
			cursor++
			{
				return true
			}
		yy199:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy212
			default:
				goto yy184
			}
		yy200:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy213
			default:
				goto yy184
			}
		yy201:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy214
			default:
				goto yy184
			}
		yy202:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy215
			default:
				goto yy184
			}
		yy203:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy216
			default:
				goto yy184
			}
		yy204:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy183
			default:
				goto yy184
			}
		yy205:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy210
			default:
				goto yy184
			}
		yy206:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy198
			default:
				goto yy184
			}
		yy207:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy206
			default:
				goto yy184
			}
		yy208:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy217
			default:
				goto yy184
			}
		yy209:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy218
			default:
				goto yy184
			}
		yy210:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy198
			default:
				goto yy184
			}
		yy211:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy219
			default:
				goto yy184
			}
		yy212:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy220
			default:
				goto yy184
			}
		yy213:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy219
			default:
				goto yy184
			}
		yy214:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy218
			default:
				goto yy184
			}
		yy215:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy207
			default:
				goto yy184
			}
		yy216:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy221
			default:
				goto yy184
			}
		yy217:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy198
			default:
				goto yy184
			}
		yy218:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy198
			default:
				goto yy184
			}
		yy219:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy218
			default:
				goto yy184
			}
		yy220:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'V':
				fallthrough
			case 'v':
				goto yy218
			default:
				goto yy184
			}
		yy221:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy222
			default:
				goto yy184
			}
		yy222:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy198
			default:
				goto yy184
			}
		yy223:
			{
				return false
			}
		}

	}
}

// Original pattern: (?i)pag(e|ing|inat)
func IsMightBePagination(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy227
			default:
				if limit <= cursor {
					goto yy235
				}
				goto yy225
			}
		yy225:
			cursor++
		yy226:
			{
				continue
			}
		yy227:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy228
			default:
				goto yy226
			}
		yy228:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy230
			default:
				goto yy229
			}
		yy229:
			cursor = marker
			goto yy226
		yy230:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy231
			case 'I':
				fallthrough
			case 'i':
				goto yy232
			default:
				goto yy229
			}
		yy231:
			cursor++
			{
				return true
			}
		yy232:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy233
			default:
				goto yy229
			}
		yy233:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy234
			case 'G':
				fallthrough
			case 'g':
				goto yy231
			default:
				goto yy229
			}
		yy234:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy231
			default:
				goto yy229
			}
		yy235:
			{
				return false
			}
		}

	}
}

// Original pattern: (?i)p(a|g|ag)?(e|ing|ination)?(=|\/)[0-9]{1,2}$
func IsMightBeLinkPagination(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	// Variable for capturing parentheses (twice the number of groups).
	var YYMAXNMATCH int = 1

	yypmatch := make([]int, YYMAXNMATCH*2)
	var yynmatch int
	_ = yynmatch

	// Autogenerated tag variables used by the lexer to track tag values.
	var yyt1 int
	_ = yyt1

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				yyt1 = cursor
				goto yy239
			default:
				if limit <= cursor {
					goto yy254
				}
				goto yy237
			}
		yy237:
			cursor++
		yy238:
			{
				continue
			}
		yy239:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case '/':
				fallthrough
			case '=':
				goto yy240
			case 'A':
				fallthrough
			case 'a':
				goto yy242
			case 'E':
				fallthrough
			case 'e':
				goto yy243
			case 'G':
				fallthrough
			case 'g':
				goto yy244
			case 'I':
				fallthrough
			case 'i':
				goto yy245
			default:
				goto yy238
			}
		yy240:
			cursor++
			yych = input[cursor]
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy246
			default:
				goto yy241
			}
		yy241:
			cursor = marker
			goto yy238
		yy242:
			cursor++
			yych = input[cursor]
			switch yych {
			case '/':
				fallthrough
			case '=':
				goto yy240
			case 'E':
				fallthrough
			case 'e':
				goto yy243
			case 'G':
				fallthrough
			case 'g':
				goto yy244
			case 'I':
				fallthrough
			case 'i':
				goto yy245
			default:
				goto yy241
			}
		yy243:
			cursor++
			yych = input[cursor]
			switch yych {
			case '/':
				fallthrough
			case '=':
				goto yy240
			default:
				goto yy241
			}
		yy244:
			cursor++
			yych = input[cursor]
			switch yych {
			case '/':
				fallthrough
			case '=':
				goto yy240
			case 'E':
				fallthrough
			case 'e':
				goto yy243
			case 'I':
				fallthrough
			case 'i':
				goto yy245
			default:
				goto yy241
			}
		yy245:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy248
			default:
				goto yy241
			}
		yy246:
			cursor++
			yych = input[cursor]
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy249
			default:
				goto yy247
			}
		yy247:
			yynmatch = 1
			yypmatch[0] = yyt1
			yypmatch[1] = cursor
			{
				if yypmatch[1] == limit {
					return true
				} else {
					continue
				}
			}
		yy248:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy250
			case 'G':
				fallthrough
			case 'g':
				goto yy243
			default:
				goto yy241
			}
		yy249:
			cursor++
			goto yy247
		yy250:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy251
			default:
				goto yy241
			}
		yy251:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy252
			default:
				goto yy241
			}
		yy252:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy253
			default:
				goto yy241
			}
		yy253:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy243
			default:
				goto yy241
			}
		yy254:
			{
				return false
			}
		}

	}
}

// Original pattern: (?i)(first|last)
func ContainsFirstLast(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 'F':
				fallthrough
			case 'f':
				goto yy258
			case 'L':
				fallthrough
			case 'l':
				goto yy259
			default:
				if limit <= cursor {
					goto yy265
				}
				goto yy256
			}
		yy256:
			cursor++
		yy257:
			{
				continue
			}
		yy258:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy260
			default:
				goto yy257
			}
		yy259:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy262
			default:
				goto yy257
			}
		yy260:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy262
			default:
				goto yy261
			}
		yy261:
			cursor = marker
			goto yy257
		yy262:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy263
			default:
				goto yy261
			}
		yy263:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy264
			default:
				goto yy261
			}
		yy264:
			cursor++
			{
				return true
			}
		yy265:
			{
				return false
			}
		}

	}
}
