// Code generated by re2c 3.1, DO NOT EDIT.
package re2go

// Original pattern: (?i)(^(comments|© reuters|please rate this|post a comment|\d+\s+(comments|users responded in))|what you think\.\.\.|add your comment|add comment|reader views|have your say|reader comments|rätta artikeln|^thanks for your comments - this feedback is now closed$)
// For convenience it will be separated into 3 regexes:
// - ^(comments|© reuters|please rate this|post a comment|\d+\s+(comments|users responded in))
// - what you think\.\.\.|add your comment|add comment|reader views|have your say|reader comments|rätta artikeln
// - ^thanks for your comments - this feedback is now closed$

// Handle (^(comments|© reuters|please rate this|post a comment|\d+\s+(comments|users responded in))
func isTerminatingBlocks1(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yyaccept := 0
			yych = input[cursor]
			switch yych {
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy3
			case 'C':
				fallthrough
			case 'c':
				goto yy5
			case 'P':
				fallthrough
			case 'p':
				goto yy6
			case 0xC2:
				goto yy7
			default:
				if limit <= cursor {
					goto yy80
				}
				goto yy1
			}
		yy1:
			cursor++
		yy2:
			{
				return false
			}
		yy3:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy8
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				goto yy3
			default:
				goto yy4
			}
		yy4:
			{
				return false
			}
		yy5:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy10
			default:
				goto yy2
			}
		yy6:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy12
			case 'O':
				fallthrough
			case 'o':
				goto yy13
			default:
				goto yy2
			}
		yy7:
			yyaccept = 0
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0xA9:
				goto yy14
			default:
				goto yy2
			}
		yy8:
			yyaccept = 1
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy8
			case 'C':
				fallthrough
			case 'c':
				goto yy15
			case 'U':
				fallthrough
			case 'u':
				goto yy16
			default:
				goto yy9
			}
		yy9:
			{
				return false
			}
		yy10:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy17
			default:
				goto yy11
			}
		yy11:
			cursor = marker
			if yyaccept == 0 {
				goto yy2
			} else {
				goto yy9
			}
		yy12:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy18
			default:
				goto yy11
			}
		yy13:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy19
			default:
				goto yy11
			}
		yy14:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy20
			default:
				goto yy11
			}
		yy15:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy21
			default:
				goto yy11
			}
		yy16:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy22
			default:
				goto yy11
			}
		yy17:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy23
			default:
				goto yy11
			}
		yy18:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy24
			default:
				goto yy11
			}
		yy19:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy25
			default:
				goto yy11
			}
		yy20:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy26
			default:
				goto yy11
			}
		yy21:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy27
			default:
				goto yy11
			}
		yy22:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy28
			default:
				goto yy11
			}
		yy23:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy29
			default:
				goto yy11
			}
		yy24:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy30
			default:
				goto yy11
			}
		yy25:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy31
			default:
				goto yy11
			}
		yy26:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy32
			default:
				goto yy11
			}
		yy27:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy33
			default:
				goto yy11
			}
		yy28:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy34
			default:
				goto yy11
			}
		yy29:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy35
			default:
				goto yy11
			}
		yy30:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy36
			default:
				goto yy11
			}
		yy31:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy37
			default:
				goto yy11
			}
		yy32:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy38
			default:
				goto yy11
			}
		yy33:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy39
			default:
				goto yy11
			}
		yy34:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy40
			default:
				goto yy11
			}
		yy35:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy41
			default:
				goto yy11
			}
		yy36:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy42
			default:
				goto yy11
			}
		yy37:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy43
			default:
				goto yy11
			}
		yy38:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy44
			default:
				goto yy11
			}
		yy39:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy45
			default:
				goto yy11
			}
		yy40:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy46
			default:
				goto yy11
			}
		yy41:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy47
			default:
				goto yy11
			}
		yy42:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy48
			default:
				goto yy11
			}
		yy43:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy49
			default:
				goto yy11
			}
		yy44:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy50
			default:
				goto yy11
			}
		yy45:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy51
			default:
				goto yy11
			}
		yy46:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy52
			default:
				goto yy11
			}
		yy47:
			cursor++
			{
				return true
			}
		yy48:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy53
			default:
				goto yy11
			}
		yy49:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy54
			default:
				goto yy11
			}
		yy50:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy55
			default:
				goto yy11
			}
		yy51:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy56
			default:
				goto yy11
			}
		yy52:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy57
			default:
				goto yy11
			}
		yy53:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy58
			default:
				goto yy11
			}
		yy54:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy59
			default:
				goto yy11
			}
		yy55:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy60
			default:
				goto yy11
			}
		yy56:
			cursor++
			{
				return true
			}
		yy57:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy61
			default:
				goto yy11
			}
		yy58:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy62
			default:
				goto yy11
			}
		yy59:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy63
			default:
				goto yy11
			}
		yy60:
			cursor++
			{
				return true
			}
		yy61:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy64
			default:
				goto yy11
			}
		yy62:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy65
			default:
				goto yy11
			}
		yy63:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy66
			default:
				goto yy11
			}
		yy64:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy67
			default:
				goto yy11
			}
		yy65:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy68
			default:
				goto yy11
			}
		yy66:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy69
			default:
				goto yy11
			}
		yy67:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy70
			default:
				goto yy11
			}
		yy68:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy71
			default:
				goto yy11
			}
		yy69:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy72
			default:
				goto yy11
			}
		yy70:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy73
			default:
				goto yy11
			}
		yy71:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy74
			default:
				goto yy11
			}
		yy72:
			cursor++
			{
				return true
			}
		yy73:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy75
			default:
				goto yy11
			}
		yy74:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy76
			default:
				goto yy11
			}
		yy75:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy77
			default:
				goto yy11
			}
		yy76:
			cursor++
			{
				return true
			}
		yy77:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy78
			default:
				goto yy11
			}
		yy78:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy79
			default:
				goto yy11
			}
		yy79:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy56
			default:
				goto yy11
			}
		yy80:
			{
				return false
			}
		}

	}
}

// Handle what you think\.\.\.|add your comment|add comment|reader views|have your say|reader comments|rätta artikeln
func isTerminatingBlocks2(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy84
			case 'H':
				fallthrough
			case 'h':
				goto yy85
			case 'R':
				fallthrough
			case 'r':
				goto yy86
			case 'W':
				fallthrough
			case 'w':
				goto yy87
			default:
				if limit <= cursor {
					goto yy172
				}
				goto yy82
			}
		yy82:
			cursor++
		yy83:
			{
				continue
			}
		yy84:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy88
			default:
				goto yy83
			}
		yy85:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy90
			default:
				goto yy83
			}
		yy86:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy91
			case 0xC3:
				goto yy92
			default:
				goto yy83
			}
		yy87:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy93
			default:
				goto yy83
			}
		yy88:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy94
			default:
				goto yy89
			}
		yy89:
			cursor = marker
			goto yy83
		yy90:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'V':
				fallthrough
			case 'v':
				goto yy95
			default:
				goto yy89
			}
		yy91:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy96
			default:
				goto yy89
			}
		yy92:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x84:
				fallthrough
			case 0xA4:
				goto yy97
			default:
				goto yy89
			}
		yy93:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy98
			default:
				goto yy89
			}
		yy94:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy99
			default:
				goto yy89
			}
		yy95:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy100
			default:
				goto yy89
			}
		yy96:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy101
			default:
				goto yy89
			}
		yy97:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy102
			default:
				goto yy89
			}
		yy98:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy103
			default:
				goto yy89
			}
		yy99:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy104
			case 'Y':
				fallthrough
			case 'y':
				goto yy105
			default:
				goto yy89
			}
		yy100:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy106
			default:
				goto yy89
			}
		yy101:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy107
			default:
				goto yy89
			}
		yy102:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy108
			default:
				goto yy89
			}
		yy103:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy109
			default:
				goto yy89
			}
		yy104:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy110
			default:
				goto yy89
			}
		yy105:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy111
			default:
				goto yy89
			}
		yy106:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy112
			default:
				goto yy89
			}
		yy107:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy113
			default:
				goto yy89
			}
		yy108:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy114
			default:
				goto yy89
			}
		yy109:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy115
			default:
				goto yy89
			}
		yy110:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy116
			default:
				goto yy89
			}
		yy111:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy117
			default:
				goto yy89
			}
		yy112:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy118
			default:
				goto yy89
			}
		yy113:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy119
			default:
				goto yy89
			}
		yy114:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy120
			default:
				goto yy89
			}
		yy115:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy121
			default:
				goto yy89
			}
		yy116:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy122
			default:
				goto yy89
			}
		yy117:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy123
			default:
				goto yy89
			}
		yy118:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy124
			default:
				goto yy89
			}
		yy119:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy125
			case 'V':
				fallthrough
			case 'v':
				goto yy126
			default:
				goto yy89
			}
		yy120:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy127
			default:
				goto yy89
			}
		yy121:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy128
			default:
				goto yy89
			}
		yy122:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy129
			default:
				goto yy89
			}
		yy123:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy130
			default:
				goto yy89
			}
		yy124:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy131
			default:
				goto yy89
			}
		yy125:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy132
			default:
				goto yy89
			}
		yy126:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy133
			default:
				goto yy89
			}
		yy127:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy134
			default:
				goto yy89
			}
		yy128:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy135
			default:
				goto yy89
			}
		yy129:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy136
			default:
				goto yy89
			}
		yy130:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy137
			default:
				goto yy89
			}
		yy131:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy138
			default:
				goto yy89
			}
		yy132:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy139
			default:
				goto yy89
			}
		yy133:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy140
			default:
				goto yy89
			}
		yy134:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy141
			default:
				goto yy89
			}
		yy135:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy142
			default:
				goto yy89
			}
		yy136:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy143
			default:
				goto yy89
			}
		yy137:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy144
			default:
				goto yy89
			}
		yy138:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy145
			default:
				goto yy89
			}
		yy139:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy146
			default:
				goto yy89
			}
		yy140:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'W':
				fallthrough
			case 'w':
				goto yy147
			default:
				goto yy89
			}
		yy141:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy148
			default:
				goto yy89
			}
		yy142:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy149
			default:
				goto yy89
			}
		yy143:
			cursor++
			{
				return true
			}
		yy144:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy150
			default:
				goto yy89
			}
		yy145:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy151
			default:
				goto yy89
			}
		yy146:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy152
			default:
				goto yy89
			}
		yy147:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy153
			default:
				goto yy89
			}
		yy148:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy154
			default:
				goto yy89
			}
		yy149:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy155
			default:
				goto yy89
			}
		yy150:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy156
			default:
				goto yy89
			}
		yy151:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy157
			default:
				goto yy89
			}
		yy152:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy158
			default:
				goto yy89
			}
		yy153:
			cursor++
			{
				return true
			}
		yy154:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy159
			default:
				goto yy89
			}
		yy155:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy160
			default:
				goto yy89
			}
		yy156:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy161
			default:
				goto yy89
			}
		yy157:
			cursor++
			{
				return true
			}
		yy158:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy162
			default:
				goto yy89
			}
		yy159:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy163
			default:
				goto yy89
			}
		yy160:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy164
			default:
				goto yy89
			}
		yy161:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy165
			default:
				goto yy89
			}
		yy162:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy166
			default:
				goto yy89
			}
		yy163:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy167
			default:
				goto yy89
			}
		yy164:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy168
			default:
				goto yy89
			}
		yy165:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy169
			default:
				goto yy89
			}
		yy166:
			cursor++
			{
				return true
			}
		yy167:
			cursor++
			{
				return true
			}
		yy168:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy170
			default:
				goto yy89
			}
		yy169:
			cursor++
			{
				return true
			}
		yy170:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy171
			default:
				goto yy89
			}
		yy171:
			cursor++
			{
				return true
			}
		yy172:
			{
				return false
			}
		}

	}
}

// Handle ^thanks for your comments - this feedback is now closed$
func isTerminatingBlocks3(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	var found bool
	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy176
			default:
				if limit <= cursor {
					goto yy231
				}
				goto yy174
			}
		yy174:
			cursor++
		yy175:
			{
				return false
			}
		yy176:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy177
			default:
				goto yy175
			}
		yy177:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy179
			default:
				goto yy178
			}
		yy178:
			cursor = marker
			goto yy175
		yy179:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy180
			default:
				goto yy178
			}
		yy180:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy181
			default:
				goto yy178
			}
		yy181:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy182
			default:
				goto yy178
			}
		yy182:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy183
			default:
				goto yy178
			}
		yy183:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'F':
				fallthrough
			case 'f':
				goto yy184
			default:
				goto yy178
			}
		yy184:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy185
			default:
				goto yy178
			}
		yy185:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy186
			default:
				goto yy178
			}
		yy186:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy187
			default:
				goto yy178
			}
		yy187:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy188
			default:
				goto yy178
			}
		yy188:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy189
			default:
				goto yy178
			}
		yy189:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy190
			default:
				goto yy178
			}
		yy190:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy191
			default:
				goto yy178
			}
		yy191:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy192
			default:
				goto yy178
			}
		yy192:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy193
			default:
				goto yy178
			}
		yy193:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy194
			default:
				goto yy178
			}
		yy194:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy195
			default:
				goto yy178
			}
		yy195:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy196
			default:
				goto yy178
			}
		yy196:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy197
			default:
				goto yy178
			}
		yy197:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy198
			default:
				goto yy178
			}
		yy198:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy199
			default:
				goto yy178
			}
		yy199:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy200
			default:
				goto yy178
			}
		yy200:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy201
			default:
				goto yy178
			}
		yy201:
			cursor++
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy202
			default:
				goto yy178
			}
		yy202:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy203
			default:
				goto yy178
			}
		yy203:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy204
			default:
				goto yy178
			}
		yy204:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy205
			default:
				goto yy178
			}
		yy205:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy206
			default:
				goto yy178
			}
		yy206:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy207
			default:
				goto yy178
			}
		yy207:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy208
			default:
				goto yy178
			}
		yy208:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'F':
				fallthrough
			case 'f':
				goto yy209
			default:
				goto yy178
			}
		yy209:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy210
			default:
				goto yy178
			}
		yy210:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy211
			default:
				goto yy178
			}
		yy211:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy212
			default:
				goto yy178
			}
		yy212:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy213
			default:
				goto yy178
			}
		yy213:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy214
			default:
				goto yy178
			}
		yy214:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy215
			default:
				goto yy178
			}
		yy215:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy216
			default:
				goto yy178
			}
		yy216:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy217
			default:
				goto yy178
			}
		yy217:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy218
			default:
				goto yy178
			}
		yy218:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy219
			default:
				goto yy178
			}
		yy219:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy220
			default:
				goto yy178
			}
		yy220:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy221
			default:
				goto yy178
			}
		yy221:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy222
			default:
				goto yy178
			}
		yy222:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'W':
				fallthrough
			case 'w':
				goto yy223
			default:
				goto yy178
			}
		yy223:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy224
			default:
				goto yy178
			}
		yy224:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy225
			default:
				goto yy178
			}
		yy225:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy226
			default:
				goto yy178
			}
		yy226:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy227
			default:
				goto yy178
			}
		yy227:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy228
			default:
				goto yy178
			}
		yy228:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy229
			default:
				goto yy178
			}
		yy229:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy230
			default:
				goto yy178
			}
		yy230:
			cursor++
			{
				found = true
				continue
			}
		yy231:
			{
				return found
			}
		}

	}
}

func IsTerminatingBlocks(input string) bool {
	return isTerminatingBlocks1(input) ||
		isTerminatingBlocks2(input) ||
		isTerminatingBlocks3(input)
}
